language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_install: composer install

script: ./CHECKLIST && composer test:unit:coverage:parallel

after_success:
  - 'curl --silent https://codecov.io/bash | bash'
